source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Segment-Amplitude_Example' do
  pod "Segment-Amplitude", :path => "../"
end

target 'Segment-Amplitude_Tests' do
  pod "Segment-Amplitude", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
