language: objective-c

osx_image: xcode7.1

before_install:
  - gem install cocoapods

script:
# pod lib lint --use-libraries --allow-warnings
- make install
- make test

notifications:
  email: false
