version: 2
jobs:
  build-and-test:
    macos:
      xcode: "11.5.0"
    steps:
      - checkout
      - run: xcrun simctl list
      - run:
          name: Install dependencies
          command: |
            sudo gem install xcpretty
            sudo gem install cocoapods
            sudo gem install cocoapods-repo-update
            make install
      - run:
          name: Run tests
          command: |
            make build
            make test
            make lint

workflows:
  version: 2
  run:
    jobs:
      - build-and-test:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
      - publish:
          context: iOS
          requires:
            - build-and-test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /[0-9]+(\.[0-9]+)*(-.+)?/
